### ISSUE TITLE
segfault on NewtonCreate()

### ISSUE THREAD

**Issue by perkinslr** [MADEAPPS/newton-dynamics#23]
I built the latest version of libNewton.so using cmake, the core libraries build fine, but when I call NewtonCreate I get the following segfault.

    #0  0x00007ffff7792e36 in dgMemoryAllocator::Malloc(int) () from /usr/local/lib64/libNewton.so
    #1  0x00007ffff77931c9 in dgMalloc(unsigned long, dgMemoryAllocator*) () from     /usr/local/lib64/libNewton.so
    #2  0x00007ffff7793817 in dgList<dgMemoryAllocator*>::dgListNode::operator new(unsigned long, dgMemoryAllocator*) () from /usr/local/lib64/libNewton.so
    #3  0x00007ffff7793638 in dgList<dgMemoryAllocator*>::Append(dgMemoryAllocator* const&) () from /usr/local/lib64/libNewton.so
    #4  0x00007ffff779295e in dgMemoryAllocator::dgMemoryAllocator() () from /usr/local/lib64/libNewton.so
    #5  0x00007ffff78774fa in NewtonCreate () from /usr/local/lib64/libNewton.so
    #6  0x0000000000400cdd in main ()

I also tried the older build system, using coreLibrary_300/projects/posix64/makefile, which builds libNewton, but cannot load it due to undefined symbols.  This happens with both the version from google's repo and github.

I still have my old version (built a year ago), and it runs fine, no segfault.

**Comment by perkinslr** [comment]
Seems likely it was either a transient problem at a particular revision, or a problem on my end, a fresh attempt worked perfectly.
